### ISSUE TITLE
Inconsistent versioning

### ISSUE THREAD

**Issue by archmoj** [colorjs/color-normalize#5]
Not sure why version 1.1.1 (the latest) was released after 1.3.0?
@dy @zeke 
cc: @etpinard
![Screenshot from 2019-06-25 15-30-33](https://user-images.githubusercontent.com/33888540/60127562-79eff600-975e-11e9-8ac6-b710b0eb2274.png)

**Comment by zeke** [comment]
I don't know how this project has historically been published to npm, but here are some thoughts:

- For one-off manual package publishing, I use [np](https://ghub.io/np). It's a nice CLI that takes care of running tests, figuring out the version, creating git tags, etc.
- For automated semantic releases, I use [semantic-release](https://ghub.io/semantic-release-cli) (`npx semantic-release-cli setup`) in conjunction with https://github.com/apps/semantic-pull-requests

**Comment by meodai** [comment]
- I also use semantic-release on some projects. I'm sure it would help a lot here as well.
- I think np might not be needed if we use https://docs.travis-ci.com/user/build-stages ?

**Comment by dy** [comment]
Hm.
Seems like some changes were made not reflected in the repository.
I have to check my old laptop.
Republished as 1.4.0 for now.

**Comment by dy** [comment]
Fixed

**Comment by zeke** [comment]
Thanks @dy 👍

In the future I can be on hand for releases if needed, but didn't want to get in the way on this version reconciliation process.
